### ISSUE TITLE
Build failing due to lv_img_conv

### ISSUE THREAD

**Issue by getlogname** [InfiniTimeOrg/InfiniSim#120]
Hi, I'm trying to build the simulator on Fedora but without success. I also tried on a fresh Ubuntu VM but had similar result, I'm obviously doing something wrong, but what?

Steps:
1) `git clone --recursive https://github.com/InfiniTimeOrg/InfiniSim.git`
2) `cd InfiniSim/`
3) `git submodule update --init --recursive`
4) `sudo dnf install cmake SDL2-devel gcc zlib-devel npm`
5) `npm install lv_font_conv@1.5.2`
6) `npm install ts-node@10.9.1 @swc/core lv_img_conv@0.3.0`
7) `cmake -S . -B build` Here I get a depreciation warning but I'm already using cmake 3.27.4 which is the latest version.
8) `cmake --build build -j4`

<details>
  <summary>Depreciation warning</summary>

```
-- Using CMake version 3.27.4
-- InfiniTime PROJECT_VERSION extracted: 1.13.0
-- The C compiler identification is GNU 13.2.1
-- The CXX compiler identification is GNU 13.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using default C++ standard 17
-- Using MONITOR_ZOOM=1
-- add subdirectory /home/brixnet/Documents/my-documents/dev/PineTime/InfiniSim/InfiniTime/src/displayapp/fonts for 'infinitime_fonts' target
-- Using /home/brixnet/Documents/my-documents/dev/PineTime/InfiniSim/node_modules/.bin/lv_font_conv to generate font files
-- Found Python3: /usr/bin/python3.11 (found version "3.11.4") found components: Interpreter 
-- add subdirectory /home/brixnet/Documents/my-documents/dev/PineTime/InfiniSim/InfiniTime/src/resources for 'GenerateResources' target
-- Using /home/brixnet/Documents/my-documents/dev/PineTime/InfiniSim/node_modules/.bin/lv_font_conv to generate font files
-- Using /home/brixnet/Documents/my-documents/dev/PineTime/InfiniSim/node_modules/.bin/lv_img_conv to generate font files
-- Looking for C++ include filesystem
-- Looking for C++ include filesystem - found
-- Performing Test CXX_FILESYSTEM_NO_LINK_NEEDED
-- Performing Test CXX_FILESYSTEM_NO_LINK_NEEDED - Success
CMake Deprecation Warning at libpng/CMakeLists.txt:27 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at libpng/CMakeLists.txt:28 (cmake_policy):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.13")  
-- Performing Test HAVE_LD_VERSION_SCRIPT
-- Performing Test HAVE_LD_VERSION_SCRIPT - Success
-- Symbol prefix: 
-- folder img: converting background.bmp to C file to include in binary
-- Configuring done (1.7s)
-- Generating done (0.1s)
-- Build files have been written to: /home/brixnet/Documents/my-documents/dev/PineTime/InfiniSim/build
```

</details>

<details>
  <summary>Failed build</summary>

```
[  0%] Building C object CMakeFiles/QCBOR.dir/InfiniTime/src/libs/QCBOR/src/ieee754.c.o
[  0%] Generating sim_background.h
[  0%] Building C object CMakeFiles/littlefs.dir/InfiniTime/src/libs/littlefs/lfs_util.c.o
[  1%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_core/lv_disp.c.o
[  1%] Building C object CMakeFiles/QCBOR.dir/InfiniTime/src/libs/QCBOR/src/qcbor_decode.c.o
[  1%] Building C object CMakeFiles/littlefs.dir/InfiniTime/src/libs/littlefs/lfs.c.o
[  1%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_core/lv_group.c.o
[  1%] Built target infinisim_img_background
[  1%] Generate fonts and images for resource package
[  1%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_core/lv_indev.c.o
[  2%] Building C object CMakeFiles/QCBOR.dir/InfiniTime/src/libs/QCBOR/src/qcbor_encode.c.o
[  3%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_core/lv_obj.c.o
[  3%] Building C object CMakeFiles/QCBOR.dir/InfiniTime/src/libs/QCBOR/src/qcbor_err_to_str.c.o
[  3%] Building C object CMakeFiles/QCBOR.dir/InfiniTime/src/libs/QCBOR/src/UsefulBuf.c.o
[  3%] Linking C static library liblittlefs.a
[  3%] Linking C static library libQCBOR.a
[  3%] Built target littlefs
[  3%] Built target QCBOR
[  3%] Generating fontawesome_weathericons.c
[  3%] Generating jetbrains_mono_42.c
[  3%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_core/lv_refr.c.o
[  3%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_core/lv_style.c.o
[  3%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_draw/lv_draw_arc.c.o
[  3%] Built target infinitime_fonts_fontawesome_weathericons
[  4%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_draw/lv_draw_blend.c.o
[  4%] Generating jetbrains_mono_76.c
[  4%] Built target infinitime_fonts_jetbrains_mono_42
[  5%] Generating jetbrains_mono_bold_20.c
[  5%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_draw/lv_draw_img.c.o
[  5%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_draw/lv_draw_label.c.o
[  5%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_draw/lv_draw_line.c.o
[  6%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_draw/lv_draw_mask.c.o
[  6%] Built target infinitime_fonts_jetbrains_mono_76
[  6%] Generating jetbrains_mono_extrabold_compressed.c
[  6%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_draw/lv_draw_rect.c.o
/usr/bin/env: ‘patch’: No such file or directory
[  6%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_draw/lv_draw_triangle.c.o
Traceback (most recent call last):
  File "/home/brixnet/Documents/my-documents/dev/PineTime/InfiniSim/InfiniTime/src/displayapp/fonts/generate.py", line 75, in <module>
    main()
  File "/home/brixnet/Documents/my-documents/dev/PineTime/InfiniSim/InfiniTime/src/displayapp/fonts/generate.py", line 70, in main
    subprocess.check_call(['/usr/bin/env', 'patch', '--silent', name+'.c', patch])
  File "/usr/lib64/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/env', 'patch', '--silent', 'jetbrains_mono_bold_20.c', 'jetbrains_mono_bold_20.c_zero.patch']' returned non-zero exit status 127.
gmake[2]: *** [fonts/CMakeFiles/infinitime_fonts_jetbrains_mono_bold_20.dir/build.make:73: fonts/jetbrains_mono_bold_20.c] Error 1
gmake[2]: *** Deleting file 'fonts/jetbrains_mono_bold_20.c'
gmake[1]: *** [CMakeFiles/Makefile2:459: fonts/CMakeFiles/infinitime_fonts_jetbrains_mono_bold_20.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
[  6%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_draw/lv_img_buf.c.o
[  7%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_draw/lv_img_cache.c.o
[  7%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_draw/lv_img_decoder.c.o
[  7%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font.c.o
[  8%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_dejavu_16_persian_hebrew.c.o
[  8%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_fmt_txt.c.o
[  8%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_loader.c.o
[  8%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_10.c.o
[  8%] Built target infinitime_fonts_jetbrains_mono_extrabold_compressed
[  9%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_12.c.o
[  9%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_12_subpx.c.o
[  9%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_14.c.o
[  9%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_16.c.o
[ 10%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_18.c.o
[ 10%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_20.c.o
[ 10%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_22.c.o
[ 10%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_24.c.o
[ 12%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_26.c.o
[ 12%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_28.c.o
[ 12%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_28_compressed.c.o
[ 13%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_30.c.o
[ 13%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_32.c.o
[ 13%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_34.c.o
[ 13%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_36.c.o
[ 14%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_38.c.o
[ 14%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_40.c.o
[ 14%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_42.c.o
[ 14%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_44.c.o
[ 15%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_46.c.o
[ 15%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_48.c.o
[ 15%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_8.c.o
[ 15%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_simsun_16_cjk.c.o
[ 16%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_unscii_16.c.o
[ 16%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_unscii_8.c.o
[ 16%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_gpu/lv_gpu_nxp_pxp.c.o
[ 17%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_gpu/lv_gpu_nxp_pxp_osa.c.o
[ 17%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_gpu/lv_gpu_stm32_dma2d.c.o
[ 17%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_gpu/lv_gpu_nxp_vglite.c.o
[ 17%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_hal/lv_hal_disp.c.o
[ 18%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_hal/lv_hal_indev.c.o
[ 18%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_hal/lv_hal_tick.c.o
[ 18%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_misc/lv_anim.c.o
[ 18%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_misc/lv_area.c.o
[ 19%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_misc/lv_async.c.o
[ 19%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_misc/lv_bidi.c.o
[ 19%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_misc/lv_color.c.o
[ 20%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_misc/lv_debug.c.o
[ 20%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_misc/lv_fs.c.o
[ 20%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_misc/lv_gc.c.o
[ 20%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_misc/lv_ll.c.o
[ 21%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_misc/lv_log.c.o
[ 21%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_misc/lv_math.c.o
[ 21%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_misc/lv_mem.c.o
[ 21%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_misc/lv_printf.c.o
[ 23%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_misc/lv_task.c.o
[ 23%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_misc/lv_templ.c.o
[ 23%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_misc/lv_txt.c.o
[ 23%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_misc/lv_txt_ap.c.o
[ 24%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_misc/lv_utils.c.o
[ 24%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_themes/lv_theme.c.o
[ 24%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_themes/lv_theme_empty.c.o
[ 25%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_themes/lv_theme_material.c.o
[ 25%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_themes/lv_theme_mono.c.o
[ 25%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_themes/lv_theme_template.c.o
[ 25%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_arc.c.o
[ 26%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_bar.c.o
[ 26%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_btn.c.o
[ 26%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_btnmatrix.c.o
[ 26%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_calendar.c.o
[ 27%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_canvas.c.o
[ 27%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_chart.c.o
[ 27%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_checkbox.c.o
[ 27%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_cont.c.o
[ 28%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_cpicker.c.o
[ 28%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_dropdown.c.o
[ 28%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_gauge.c.o
[ 29%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_img.c.o
[ 29%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_imgbtn.c.o
[ 29%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_keyboard.c.o
[ 29%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_label.c.o
/home/brixnet/Documents/my-documents/dev/PineTime/InfiniSim/node_modules/ts-node/src/transpilers/swc.ts:262
      throw new Error(
            ^
[ 30%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_led.c.o
Error: @swc/core threw an error when attempting to validate swc compiler options.
You may be using an old version of swc which does not support the options used by ts-node.
Try upgrading to the latest version of swc.
Error message from swc:
Failed to deserialize buffer as swc::config::Options
JSON: {"sourceMaps":true,"module":{"noInterop":false,"type":"commonjs","strictMode":true,"ignoreDynamic":false},"swcrc":false,"jsc":{"parser":{"syntax":"typescript","tsx":false,"dynamicImport":true,"importAssertions":true},"target":"es5","transform":{"legacyDecorator":true,"react":{"throwIfNamespace":false,"useBuiltins":false,"runtime":"automatic"}},"keepClassNames":false,"experimental":{"keepImportAssertions":true}}}

Caused by:
    unknown field `keepImportAssertions`, expected one of `plugins`, `keepImportAttributes`, `emitAssertForImportAttributes`, `cacheRoot`, `disableBuiltinTransformsForInternalTesting` at line 1 column 415
    at createVariant (/home/brixnet/Documents/my-documents/dev/PineTime/InfiniSim/node_modules/ts-node/src/transpilers/swc.ts:262:13)
    at createSwcOptions (/home/brixnet/Documents/my-documents/dev/PineTime/InfiniSim/node_modules/ts-node/src/transpilers/swc.ts:211:25)
    at create (/home/brixnet/Documents/my-documents/dev/PineTime/InfiniSim/node_modules/ts-node/src/transpilers/swc.ts:56:41)
    at createTranspiler (/home/brixnet/Documents/my-documents/dev/PineTime/InfiniSim/node_modules/ts-node/src/index.ts:784:16)
    at createTranspileOnlyGetOutputFunction (/home/brixnet/Documents/my-documents/dev/PineTime/InfiniSim/node_modules/ts-node/src/index.ts:1341:28)
    at createFromPreloadedConfig (/home/brixnet/Documents/my-documents/dev/PineTime/InfiniSim/node_modules/ts-node/src/index.ts:1404:34)
    at phase4 (/home/brixnet/Documents/my-documents/dev/PineTime/InfiniSim/node_modules/ts-node/src/bin.ts:543:44)
    at bootstrap (/home/brixnet/Documents/my-documents/dev/PineTime/InfiniSim/node_modules/ts-node/src/bin.ts:95:10)
    at main (/home/brixnet/Documents/my-documents/dev/PineTime/InfiniSim/node_modules/ts-node/src/bin.ts:55:10)
    at Object.<anonymous> (/home/brixnet/Documents/my-documents/dev/PineTime/InfiniSim/node_modules/ts-node/src/bin.ts:800:3)
[ 30%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_line.c.o
[ 30%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_linemeter.c.o
Traceback (most recent call last):
  File "/home/brixnet/Documents/my-documents/dev/PineTime/InfiniSim/InfiniTime/src/resources/generate-img.py", line 56, in <module>
    main()
  File "/home/brixnet/Documents/my-documents/dev/PineTime/InfiniSim/InfiniTime/src/resources/generate-img.py", line 51, in main
    subprocess.check_call(line)
  File "/usr/lib64/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/brixnet/Documents/my-documents/dev/PineTime/InfiniSim/node_modules/.bin/lv_img_conv', '/home/brixnet/Documents/my-documents/dev/PineTime/InfiniSim/InfiniTime/src/resources/images/pine_logo.png', '--force', '--output-file', 'pine_small.bin', '--color-format', 'CF_TRUE_COLOR_ALPHA', '--output-format', 'bin', '--binary-format', 'ARGB8565_RBSWAP']' returned non-zero exit status 1.
[ 30%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_list.c.o
gmake[2]: *** [resources/CMakeFiles/GenerateResources.dir/build.make:73: resources/CMakeFiles/GenerateResources] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:615: resources/CMakeFiles/GenerateResources.dir/all] Error 2
[ 31%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_msgbox.c.o
[ 31%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_objmask.c.o
[ 31%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_objx_templ.c.o
[ 32%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_page.c.o
[ 32%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_roller.c.o
[ 32%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_slider.c.o
[ 32%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_spinbox.c.o
[ 34%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_spinner.c.o
[ 34%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_switch.c.o
[ 34%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_table.c.o
[ 35%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_textarea.c.o
[ 35%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_tabview.c.o
[ 35%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_tileview.c.o
[ 35%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_win.c.o
[ 35%] Building C object CMakeFiles/sim-base.dir/lv_drivers/display/GC9A01.c.o
[ 36%] Building C object CMakeFiles/sim-base.dir/lv_drivers/display/ILI9341.c.o
[ 36%] Building C object CMakeFiles/sim-base.dir/lv_drivers/display/R61581.c.o
[ 36%] Building C object CMakeFiles/sim-base.dir/lv_drivers/display/SHARP_MIP.c.o
[ 37%] Building C object CMakeFiles/sim-base.dir/lv_drivers/display/SSD1963.c.o
[ 37%] Building C object CMakeFiles/sim-base.dir/lv_drivers/display/ST7565.c.o
[ 37%] Building C object CMakeFiles/sim-base.dir/lv_drivers/display/UC1610.c.o
[ 37%] Building C object CMakeFiles/sim-base.dir/lv_drivers/display/drm.c.o
[ 38%] Building C object CMakeFiles/sim-base.dir/lv_drivers/display/fbdev.c.o
[ 38%] Building C object CMakeFiles/sim-base.dir/lv_drivers/display/monitor.c.o
[ 38%] Building C object CMakeFiles/sim-base.dir/lv_drivers/indev/AD_touch.c.o
[ 38%] Building C object CMakeFiles/sim-base.dir/lv_drivers/gtkdrv/gtkdrv.c.o
[ 39%] Building C object CMakeFiles/sim-base.dir/lv_drivers/indev/FT5406EE8.c.o
[ 39%] Building C object CMakeFiles/sim-base.dir/lv_drivers/indev/XPT2046.c.o
[ 39%] Building C object CMakeFiles/sim-base.dir/lv_drivers/indev/evdev.c.o
[ 39%] Building C object CMakeFiles/sim-base.dir/lv_drivers/indev/keyboard.c.o
[ 40%] Building C object CMakeFiles/sim-base.dir/lv_drivers/indev/mouse.c.o
[ 40%] Building C object CMakeFiles/sim-base.dir/lv_drivers/indev/libinput.c.o
[ 40%] Building C object CMakeFiles/sim-base.dir/lv_drivers/indev/mousewheel.c.o
[ 41%] Building C object CMakeFiles/sim-base.dir/lv_drivers/win32drv/win32drv.c.o
[ 41%] Building C object CMakeFiles/sim-base.dir/lv_drivers/win_drv.c.o
[ 41%] Building CXX object CMakeFiles/sim-base.dir/sim/FreeRTOS.cpp.o
[ 41%] Building CXX object CMakeFiles/sim-base.dir/sim/task.cpp.o
[ 42%] Building CXX object CMakeFiles/sim-base.dir/sim/timers.cpp.o
[ 42%] Building CXX object CMakeFiles/sim-base.dir/sim/queue.cpp.o
[ 42%] Building CXX object CMakeFiles/sim-base.dir/sim/portmacro_cmsis.cpp.o
[ 42%] Building CXX object CMakeFiles/sim-base.dir/sim/libraries/delay/nrf_delay.cpp.o
[ 43%] Building CXX object CMakeFiles/sim-base.dir/sim/nrfx/hal/nrf_gpio.cpp.o
[ 43%] Building CXX object CMakeFiles/sim-base.dir/sim/nrfx/hal/nrf_rtc.cpp.o
[ 43%] Building CXX object CMakeFiles/sim-base.dir/sim/nrfx/mdk/nrf52.cpp.o
[ 45%] Linking CXX static library libsim-base.a
[ 45%] Built target sim-base
gmake: *** [Makefile:136: all] Error 2
```

</details>

Thanks for reading

**Comment by FintasticMan** [comment]
That deprecation warning isn't the source of the error, that's just an outdated minimum cmake version from libpng. The issue is that you don't have the `patch` program installed. That can be installed with the `patch` package.

**Comment by getlogname** [comment]
Thanks, I installed `patch` wich resolved my initial problem, but I now have an issue with `swc`:
 <details>
  <summary>Failed build</summary>

```
[  0%] Generating sim_background.h
[  0%] Building C object CMakeFiles/QCBOR.dir/InfiniTime/src/libs/QCBOR/src/ieee754.c.o
[  0%] Building C object CMakeFiles/littlefs.dir/InfiniTime/src/libs/littlefs/lfs_util.c.o
[  1%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_core/lv_disp.c.o
[  1%] Building C object CMakeFiles/QCBOR.dir/InfiniTime/src/libs/QCBOR/src/qcbor_decode.c.o
[  1%] Building C object CMakeFiles/littlefs.dir/InfiniTime/src/libs/littlefs/lfs.c.o
[  1%] Built target infinisim_img_background
[  1%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_core/lv_group.c.o
[  1%] Generate fonts and images for resource package
[  1%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_core/lv_indev.c.o
[  2%] Building C object CMakeFiles/QCBOR.dir/InfiniTime/src/libs/QCBOR/src/qcbor_encode.c.o
[  3%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_core/lv_obj.c.o
[  3%] Building C object CMakeFiles/QCBOR.dir/InfiniTime/src/libs/QCBOR/src/qcbor_err_to_str.c.o
[  3%] Building C object CMakeFiles/QCBOR.dir/InfiniTime/src/libs/QCBOR/src/UsefulBuf.c.o
[  3%] Linking C static library liblittlefs.a
[  3%] Linking C static library libQCBOR.a
[  3%] Built target littlefs
[  3%] Generating fontawesome_weathericons.c
[  3%] Built target QCBOR
[  3%] Generating jetbrains_mono_42.c
[  3%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_core/lv_refr.c.o
[  3%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_core/lv_style.c.o
[  3%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_draw/lv_draw_arc.c.o
[  3%] Built target infinitime_fonts_fontawesome_weathericons
[  4%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_draw/lv_draw_blend.c.o
[  4%] Generating jetbrains_mono_76.c
[  4%] Built target infinitime_fonts_jetbrains_mono_42
[  5%] Generating jetbrains_mono_bold_20.c
[  5%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_draw/lv_draw_img.c.o
[  5%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_draw/lv_draw_label.c.o
[  5%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_draw/lv_draw_line.c.o
[  6%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_draw/lv_draw_mask.c.o
[  6%] Built target infinitime_fonts_jetbrains_mono_76
[  6%] Generating jetbrains_mono_extrabold_compressed.c
[  6%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_draw/lv_draw_rect.c.o
[  6%] Built target infinitime_fonts_jetbrains_mono_bold_20
[  6%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_draw/lv_draw_triangle.c.o
[  6%] Generating lv_font_navi_80.c
[  6%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_draw/lv_img_buf.c.o
[  7%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_draw/lv_img_cache.c.o
[  7%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_draw/lv_img_decoder.c.o
[  7%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font.c.o
[  8%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_dejavu_16_persian_hebrew.c.o
[  8%] Built target infinitime_fonts_jetbrains_mono_extrabold_compressed
[  8%] Generating lv_font_sys_48.c
[  8%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_fmt_txt.c.o
[  8%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_loader.c.o
[  8%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_10.c.o
[  9%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_12.c.o
[  9%] Built target infinitime_fonts_lv_font_navi_80
[ 10%] Generating open_sans_light.c
[ 10%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_12_subpx.c.o
[ 10%] Built target infinitime_fonts_lv_font_sys_48
[ 10%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_14.c.o
[ 10%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_16.c.o
[ 12%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_18.c.o
[ 12%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_20.c.o
[ 12%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_22.c.o
[ 12%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_24.c.o
[ 13%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_26.c.o
[ 13%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_28.c.o
[ 13%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_28_compressed.c.o
[ 14%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_30.c.o
[ 14%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_32.c.o
[ 14%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_34.c.o
[ 14%] Built target infinitime_fonts_open_sans_light
[ 15%] Generating pnglibconf.c
[ 15%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_36.c.o
[ 16%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_38.c.o
[ 16%] Built target pnglibconf_c
[ 17%] Generating scripts/pnglibconf.c
[ 17%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_40.c.o
[ 17%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_42.c.o
[ 17%] Built target scripts_pnglibconf_c
[ 17%] Generating pngprefix.h
[ 17%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_44.c.o
[ 18%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_46.c.o
[ 18%] Built target pngprefix_h
[ 18%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_48.c.o
[ 18%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_8.c.o
[ 18%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_simsun_16_cjk.c.o
[ 19%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_unscii_16.c.o
[ 19%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_unscii_8.c.o
[ 19%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_gpu/lv_gpu_nxp_pxp.c.o
[ 20%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_gpu/lv_gpu_nxp_pxp_osa.c.o
[ 20%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_gpu/lv_gpu_nxp_vglite.c.o
[ 20%] Generating scripts/symbols.out
[ 20%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_gpu/lv_gpu_stm32_dma2d.c.o
[ 21%] Building C object external/miniz/CMakeFiles/miniz.dir/miniz.c.o
[ 21%] Built target scripts_symbols_out
/home/brixnet/Documents/my-documents/dev/PineTime/InfiniSim/external/miniz/miniz.c:3089:9: note: ‘#pragma message: Using fopen, ftello, fseeko, stat() etc. path for file I/O - this path may not support large files.’
 3089 | #pragma message("Using fopen, ftello, fseeko, stat() etc. path for file I/O - this path may not support large files.")
      |         ^~~~~~~
[ 21%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_hal/lv_hal_disp.c.o
[ 23%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_hal/lv_hal_indev.c.o
[ 23%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_hal/lv_hal_tick.c.o
[ 23%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_misc/lv_anim.c.o
[ 23%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_misc/lv_area.c.o
/home/brixnet/Documents/my-documents/dev/PineTime/InfiniSim/node_modules/ts-node/src/transpilers/swc.ts:262
      throw new Error(
            ^
Error: @swc/core threw an error when attempting to validate swc compiler options.
You may be using an old version of swc which does not support the options used by ts-node.
Try upgrading to the latest version of swc.
Error message from swc:
Failed to deserialize buffer as swc::config::Options
JSON: {"sourceMaps":true,"module":{"noInterop":false,"type":"commonjs","strictMode":true,"ignoreDynamic":false},"swcrc":false,"jsc":{"parser":{"syntax":"typescript","tsx":false,"dynamicImport":true,"importAssertions":true},"target":"es5","transform":{"legacyDecorator":true,"react":{"throwIfNamespace":false,"useBuiltins":false,"runtime":"automatic"}},"keepClassNames":false,"experimental":{"keepImportAssertions":true}}}

Caused by:
    unknown field `keepImportAssertions`, expected one of `plugins`, `keepImportAttributes`, `emitAssertForImportAttributes`, `cacheRoot`, `disableBuiltinTransformsForInternalTesting` at line 1 column 415
    at createVariant (/home/brixnet/Documents/my-documents/dev/PineTime/InfiniSim/node_modules/ts-node/src/transpilers/swc.ts:262:13)
    at createSwcOptions (/home/brixnet/Documents/my-documents/dev/PineTime/InfiniSim/node_modules/ts-node/src/transpilers/swc.ts:211:25)
    at create (/home/brixnet/Documents/my-documents/dev/PineTime/InfiniSim/node_modules/ts-node/src/transpilers/swc.ts:56:41)
    at createTranspiler (/home/brixnet/Documents/my-documents/dev/PineTime/InfiniSim/node_modules/ts-node/src/index.ts:784:16)
    at createTranspileOnlyGetOutputFunction (/home/brixnet/Documents/my-documents/dev/PineTime/InfiniSim/node_modules/ts-node/src/index.ts:1341:28)
    at createFromPreloadedConfig (/home/brixnet/Documents/my-documents/dev/PineTime/InfiniSim/node_modules/ts-node/src/index.ts:1404:34)
    at phase4 (/home/brixnet/Documents/my-documents/dev/PineTime/InfiniSim/node_modules/ts-node/src/bin.ts:543:44)
    at bootstrap (/home/brixnet/Documents/my-documents/dev/PineTime/InfiniSim/node_modules/ts-node/src/bin.ts:95:10)
    at main (/home/brixnet/Documents/my-documents/dev/PineTime/InfiniSim/node_modules/ts-node/src/bin.ts:55:10)
    at Object.<anonymous> (/home/brixnet/Documents/my-documents/dev/PineTime/InfiniSim/node_modules/ts-node/src/bin.ts:800:3)
[ 24%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_misc/lv_async.c.o
[ 24%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_misc/lv_bidi.c.o
[ 24%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_misc/lv_color.c.o
[ 25%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_misc/lv_debug.c.o
Traceback (most recent call last):
  File "/home/brixnet/Documents/my-documents/dev/PineTime/InfiniSim/InfiniTime/src/resources/generate-img.py", line 56, in <module>
    main()
  File "/home/brixnet/Documents/my-documents/dev/PineTime/InfiniSim/InfiniTime/src/resources/generate-img.py", line 51, in main
    subprocess.check_call(line)
  File "/usr/lib64/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/brixnet/Documents/my-documents/dev/PineTime/InfiniSim/node_modules/.bin/lv_img_conv', '/home/brixnet/Documents/my-documents/dev/PineTime/InfiniSim/InfiniTime/src/resources/images/pine_logo.png', '--force', '--output-file', 'pine_small.bin', '--color-format', 'CF_TRUE_COLOR_ALPHA', '--output-format', 'bin', '--binary-format', 'ARGB8565_RBSWAP']' returned non-zero exit status 1.
[ 25%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_misc/lv_fs.c.o
[ 25%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_misc/lv_gc.c.o
gmake[2]: *** [resources/CMakeFiles/GenerateResources.dir/build.make:73: resources/CMakeFiles/GenerateResources] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:615: resources/CMakeFiles/GenerateResources.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
[ 25%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_misc/lv_ll.c.o
[ 26%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_misc/lv_log.c.o
[ 26%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_misc/lv_math.c.o
[ 26%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_misc/lv_mem.c.o
[ 26%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_misc/lv_printf.c.o
[ 27%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_misc/lv_task.c.o
[ 27%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_misc/lv_templ.c.o
[ 27%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_misc/lv_txt.c.o
[ 27%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_misc/lv_txt_ap.c.o
[ 28%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_misc/lv_utils.c.o
[ 28%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_themes/lv_theme.c.o
[ 28%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_themes/lv_theme_empty.c.o
[ 29%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_themes/lv_theme_material.c.o
[ 29%] Linking C static library libminiz.a
[ 29%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_themes/lv_theme_mono.c.o
[ 29%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_themes/lv_theme_template.c.o
[ 29%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_arc.c.o
[ 29%] Built target miniz
[ 30%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_bar.c.o
[ 30%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_btn.c.o
[ 30%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_btnmatrix.c.o
[ 30%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_calendar.c.o
[ 31%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_canvas.c.o
[ 31%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_chart.c.o
[ 31%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_checkbox.c.o
[ 31%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_cont.c.o
[ 32%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_cpicker.c.o
[ 32%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_dropdown.c.o
[ 32%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_gauge.c.o
[ 34%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_img.c.o
[ 34%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_imgbtn.c.o
[ 34%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_keyboard.c.o
[ 34%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_label.c.o
[ 35%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_led.c.o
[ 35%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_line.c.o
[ 35%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_linemeter.c.o
[ 35%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_list.c.o
[ 36%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_msgbox.c.o
[ 36%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_objmask.c.o
[ 36%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_objx_templ.c.o
[ 37%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_page.c.o
[ 37%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_roller.c.o
[ 37%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_slider.c.o
[ 37%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_spinbox.c.o
[ 38%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_spinner.c.o
[ 38%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_switch.c.o
[ 38%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_table.c.o
[ 38%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_tabview.c.o
[ 39%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_textarea.c.o
[ 39%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_tileview.c.o
[ 39%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_win.c.o
[ 39%] Building C object CMakeFiles/sim-base.dir/lv_drivers/display/GC9A01.c.o
[ 40%] Building C object CMakeFiles/sim-base.dir/lv_drivers/display/ILI9341.c.o
[ 40%] Building C object CMakeFiles/sim-base.dir/lv_drivers/display/R61581.c.o
[ 40%] Building C object CMakeFiles/sim-base.dir/lv_drivers/display/SHARP_MIP.c.o
[ 41%] Building C object CMakeFiles/sim-base.dir/lv_drivers/display/ST7565.c.o
[ 41%] Building C object CMakeFiles/sim-base.dir/lv_drivers/display/SSD1963.c.o
[ 41%] Building C object CMakeFiles/sim-base.dir/lv_drivers/display/UC1610.c.o
[ 41%] Building C object CMakeFiles/sim-base.dir/lv_drivers/display/drm.c.o
[ 42%] Building C object CMakeFiles/sim-base.dir/lv_drivers/display/fbdev.c.o
[ 42%] Building C object CMakeFiles/sim-base.dir/lv_drivers/display/monitor.c.o
[ 42%] Building C object CMakeFiles/sim-base.dir/lv_drivers/gtkdrv/gtkdrv.c.o
[ 43%] Building C object CMakeFiles/sim-base.dir/lv_drivers/indev/FT5406EE8.c.o
[ 43%] Building C object CMakeFiles/sim-base.dir/lv_drivers/indev/AD_touch.c.o
[ 43%] Building C object CMakeFiles/sim-base.dir/lv_drivers/indev/XPT2046.c.o
[ 43%] Building C object CMakeFiles/sim-base.dir/lv_drivers/indev/evdev.c.o
[ 43%] Building C object CMakeFiles/sim-base.dir/lv_drivers/indev/keyboard.c.o
[ 45%] Building C object CMakeFiles/sim-base.dir/lv_drivers/indev/libinput.c.o
[ 45%] Building C object CMakeFiles/sim-base.dir/lv_drivers/indev/mouse.c.o
[ 45%] Building C object CMakeFiles/sim-base.dir/lv_drivers/indev/mousewheel.c.o
[ 46%] Building C object CMakeFiles/sim-base.dir/lv_drivers/win32drv/win32drv.c.o
[ 46%] Building C object CMakeFiles/sim-base.dir/lv_drivers/win_drv.c.o
[ 46%] Building CXX object CMakeFiles/sim-base.dir/sim/FreeRTOS.cpp.o
[ 46%] Building CXX object CMakeFiles/sim-base.dir/sim/task.cpp.o
[ 47%] Building CXX object CMakeFiles/sim-base.dir/sim/timers.cpp.o
[ 47%] Building CXX object CMakeFiles/sim-base.dir/sim/queue.cpp.o
[ 47%] Building CXX object CMakeFiles/sim-base.dir/sim/portmacro_cmsis.cpp.o
[ 47%] Building CXX object CMakeFiles/sim-base.dir/sim/libraries/delay/nrf_delay.cpp.o
[ 48%] Building CXX object CMakeFiles/sim-base.dir/sim/nrfx/hal/nrf_gpio.cpp.o
[ 48%] Building CXX object CMakeFiles/sim-base.dir/sim/nrfx/hal/nrf_rtc.cpp.o
[ 48%] Building CXX object CMakeFiles/sim-base.dir/sim/nrfx/mdk/nrf52.cpp.o
[ 49%] Linking CXX static library libsim-base.a
[ 49%] Built target sim-base
gmake: *** [Makefile:136: all] Error 2
```
</details>

**Comment by NeroBurner** [comment]
You can try the `libpng_system_lib` branch. On there I tried to build with the `fedora:latest` docker image (I think that is version 35, not sure though). 

I've updated the readme on that branch as well

https://github.com/InfiniTimeOrg/InfiniSim/tree/libpng_system_lib

```sh
sudo dnf install cmake SDL2-devel g++ npm patch perl libpng-devel
```

**Comment by getlogname** [comment]
I'm still getting the `swc` errors, tried on both latest Fedora 38 and fresh Fedora 35 VM. However, it works with `cmake -S . -B build -DBUILD_RESOURCES=OFF`.

I'm trying to set-up a safe dev environment to write watch faces and applications without bricking my sealed PineTime, but for this I need `-DBUILD_RESOURCES=ON` , right?

**Comment by NeroBurner** [comment]
Only if you want to write apps which use resources from the littles filesystem. If you write apps just part of the regular firmware you can build without the resources generation. So yes you could develop without the resources.

I tested the fedora image last week. Maybe something in the lv_img_conv tool did change since then? If so this should be addressed as well 🤔 (generally I mean)

**Comment by getlogname** [comment]
OK thanks for your help, I'll check again later if the build passes with the default parameters before closing this issue.

**Comment by FintasticMan** [comment]
Some other people have reported issues like this, where `@swc/core` has received an update that breaks the build. You can apparently fix it by pinning it to an older version.

**Comment by getlogname** [comment]
You're right, I managed to build using swc v1.3.80.
Following the main branch readme steps with `npm install ts-node@10.9.1 @swc/core@1.3.80 lv_img_conv@0.3.0` works on latest Fedora.

**Comment by FintasticMan** [comment]
Does it fail with 1.3.81? If so, we can try to figure out what changed in that version that causes the issue.

**Comment by getlogname** [comment]
I just picked a random version, my bad. It seems **1.3.83** introduced this bug.

**Comment by FintasticMan** [comment]
Thanks for figuring that out! Then I think it's likely one of the following commits that introduced the issue: [ee75756](https://github.com/swc-project/swc/commit/ee7575695de6dad140457ffb8bb8f0ac80c4dcdc), [0db25a2](https://github.com/swc-project/swc/commit/0db25a252cf35e4b64b38bde9f34a2f33eb2f662) or [a86e9f3](https://github.com/swc-project/swc/commit/a86e9f3bb5bd490ebf0b18fe7349a2b0fbc0c45f).

**Comment by FintasticMan** [comment]
Fixed by InfiniTimeOrg/InfiniTime#1863. @NeroBurner could you close this issue?
